apiVersion: v1
kind: Service
metadata:
  name: {{ include "camunda-fdw.fullname" . }}-db-ref
  labels:
    {{- include "camunda-fdw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: http-db-ref
      protocol: TCP
      name: http-db-ref
  selector:
    {{- include "camunda-fdw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/tier: db-ref
