apiVersion: v1
kind: Service
metadata:
  name: {{ include "camunda-fdw.fullname" . }}-webserver2
  labels:
    {{- include "camunda-fdw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http2
      protocol: TCP
      name: http2
  selector:
    {{- include "camunda-fdw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/tier: webserver2
