{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "camunda-fdw.serviceAccountName" . }}
  labels:
{{ include "camunda-fdw.labels" . | nindent 4 }}
{{- end -}}
