FROM python:3.7 AS migration-tenant

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN apt update && apt install -y postgresql-client && apt clean
ENV CONFIG_DIRECTORY /app/
ENV INFRA_FILE infra.yaml
COPY migrate.py .
ENTRYPOINT ["python", "./migrate.py"]

FROM migration-tenant AS migration-tenant-moodle
COPY iomad/config.yaml ./
COPY iomad/db.yaml ./
COPY iomad/dump_data.sql ./
COPY iomad/dump_db_empty.sql ./
COPY iomad/sequence.sql ./