apiVersion: v1
kind: Service
metadata:
  name: {{ include "moodle-fdw.fullname" . }}-webserver
  labels:
    {{- include "moodle-fdw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moodle-fdw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/tier: webserver    
