version: "3.7"
services:
  get_test:
    image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION:-7.2}"
    volumes:
      - "./iomad/iomad:/var/www/html"
      - "./iomad/moodle-docker/assets/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
      - "./iomad/moodle-docker/assets/web/apache2_mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"

    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBHOST: db
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST:-localhost}"
      MOODLE_DOCKER_WEB_PORT: "${MOODLE_DOCKER_WEB_PORT:-8000}"
    entrypoint: > 
      bash -c "php admin/tool/generator/cli/maketestplan.php --shortname="CP21667" --size="XS" > result
      && export TESTPLAN=`cat result | sed -n '1p'`
      && export USERS=`cat result | sed -n '2p'`
      && echo $$TESTPLAN $$USERS
      && wget $$TESTPLAN -o testplan.jmx
      && wget $$USERS -o users.csv"