apiVersion: v1
kind: Service
metadata:
  name: {{ include "camunda.fullname" . }}-db
  labels:
    {{- include "camunda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: http-db
      protocol: TCP
      name: http-db
  selector:
    {{- include "camunda.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/tier: db
