apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: moodle-dump-
spec:
  entrypoint: moodle-dump
  parallelism: 3
  #onExit: helm-remove-moodle
  volumes:   
  - name: git
    persistentVolumeClaim:
      claimName: git    
  - name: workdir
    emptyDir: {}
  
  arguments:
    parameters:
    - name: xp-name
      value: moodle
    - name: tests
#    artifacts:
#    - name: moodle-chart
#      git:
#        repo: https://github.com/CloudLargeScale-UCLouvain/LiveMigrations

  templates:
  - name: moodle-dump
    steps:
    - - name: save-manager-scripts
        template: volume-manager-scripts
    - - name: install-moodle
        template: helm-install-moodle
        arguments:
          parameters:
          - name: size
            value: "{{item.size}}"        
          - name: nb-users
            value: "{{item.nb-users}}"        
          - name: nb-courses
            value: "{{item.nb-courses}}"        
          artifacts:
          - name: manager-scripts
            from: "{{steps.save-manager-scripts.outputs.artifacts.manager-scripts}}"  
        withParam: "{{workflow.parameters.tests}}"
    - - name: source-dump
        template: source-dump-mono                
        arguments:        
          parameters:
          - name: size
            value: "{{item.size}}"        
          - name: nb-users
            value: "{{item.nb-users}}"        
          - name: nb-courses
            value: "{{item.nb-courses}}"  
          artifacts:
          - name: empty-dump
            from: "{{steps.save-manager-scripts.outputs.artifacts.empty-dump}}"
        withParam: "{{workflow.parameters.tests}}"
    - - name: init-data
        template: make-test-site
        arguments:
          artifacts:
          - name: iomad-www
            from: "{{steps.save-manager-scripts.outputs.artifacts.iomad-www}}"
          parameters:
          - name: size
            value: "{{item.size}}"        
          - name: nb-users
            value: "{{item.nb-users}}"        
          - name: nb-courses
            value: "{{item.nb-courses}}"  
        withParam: "{{workflow.parameters.tests}}"    
    - - name: dump-db
        template: dump-database
        arguments:
          parameters:
          - name: size
            value: "{{item.size}}"        
          - name: nb-users
            value: "{{item.nb-users}}"        
          - name: nb-courses
            value: "{{item.nb-courses}}"  
        withParam: "{{workflow.parameters.tests}}"            
       
#    - - name: remove-moodle
#        template: helm-remove-moodle
##############################################################################
  - name: volume-manager-scripts
    script:
      image: alpine/git
      volumeMounts:
      - mountPath: /git
        name: git 
      command: [sh]        
      source: |-
        git clone --depth 1 https://github.com/guillaumerosinosky/iomad.git /var/www/html        
    outputs:
      artifacts:
      - name: manager-scripts
        path: /git/manager-scripts
      - name: empty-dump
        path: /git/iomad/dump_db_empty.sql
      - name: iomad-www
        path: /var/www/html
#################################
  - name: helm-install-moodle
    inputs:
      artifacts:
      - name: manager-scripts
        path: /git/manager-scripts
        mode: 0755  
      parameters:
      - name: size
      - name: nb-users
      - name: nb-courses
    script:
      image: alpine/helm
      command: [sh]    
      source: |-
        cd /git/manager-scripts/helm/moodle
        export XP_NAME={{workflow.parameters.xp-name}}-{{inputs.parameters.size}}-{{inputs.parameters.nb-users}}-{{inputs.parameters.nb-courses}}
        helm install $XP_NAME .
        apk add --update curl 
        echo ""
        # wait for db before next step
        export PGPASSWORD=m@0dl3ing

################################
  - name: source-dump-mono
    inputs:
      artifacts:
      - name: empty-dump
        path: /git/empty-dump.sql
        mode: 0755
      parameters:
      - name: size
      - name: nb-users
      - name: nb-courses
    script:
      image: grosinosky/migration-tenant:iomad-36 
      command: [sh]    
      source: |-
        export PGPASSWORD=m@0dl3ing
        export XP_NAME={{workflow.parameters.xp-name}}-{{inputs.parameters.size}}-{{inputs.parameters.nb-users}}-{{inputs.parameters.nb-courses}}
        while ! pg_isready -h ${XP_NAME}-db  > /dev/null 2> /dev/null; do
          echo "Connecting to ${XP_NAME}-db  Failed"
          sleep 1
        done  

        psql -U moodle -h $XP_NAME-db < /git/empty-dump.sql

####################################
  - name: make-test-site
    inputs:
      parameters:
      - name: size
      - name: nb-users
      - name: nb-courses
      artifacts:
      - name: iomad-www
        path: /var/www/html

    script:
      image: moodlehq/moodle-php-apache:7.2
      env:
      - name: MOODLE_DOCKER_DBHOST
        value: "{{workflow.parameters.xp-name}}-{{inputs.parameters.size}}-{{inputs.parameters.nb-users}}-{{inputs.parameters.nb-courses}}-db"
      - name: MOODLE_DOCKER_DBNAME
        value: moodle
      - name: MOODLE_DOCKER_DBPASS
        value: m@0dl3ing
      - name: MOODLE_DOCKER_DBTYPE
        value: pgsql
      - name: MOODLE_DOCKER_DBUSER
        value: moodle
      - name: MOODLE_DOCKER_WEB_HOST
        value: localhost
      - name: MOODLE_DOCKER_BROWSER
        value: firefox
      - name: MOODLE_DOCKER_WEB_PORT
        value: "80"
      command: [bash]   
      source : |
        echo "{{workflow.parameters.xp-name}}-{{inputs.parameters.size}}-{{inputs.parameters.nb-users}}-{{inputs.parameters.nb-courses}}-moodle-db"
        echo "php admin/tool/iomadsite/cli/maketestsite.php --size={{inputs.parameters.size}} --nb_users={{inputs.parameters.nb-users}} --nb_courses={{inputs.parameters.nb-courses}}"
        php admin/tool/iomadsite/cli/maketestsite.php --size={{inputs.parameters.size}} --nb_users={{inputs.parameters.nb-users}} --nb_courses={{inputs.parameters.nb-courses}}

###########################################          
  - name: dump-database
    inputs:
      parameters:
      - name: size
      - name: nb-users
      - name: nb-courses    
    script:
      image: postgres
      command: [sh]    
      source: |-
        export PGPASSWORD=m@0dl3ing
        export XP_NAME={{workflow.parameters.xp-name}}-{{inputs.parameters.size}}-{{inputs.parameters.nb-users}}-{{inputs.parameters.nb-courses}}
        pg_dump --column-inserts --data-only -U moodle -h $XP_NAME-db > /dump1.sql
    outputs:
      artifacts:
      - name: dump1
        path: /dump1.sql
        archive:
          none: {}        
        s3: 
          endpoint: argo-artifacts.default:9000  
          bucket: experiments
          insecure: true
          key: "dump/moodle/{{workflow.parameters.xp-name}}-{{inputs.parameters.size}}-{{inputs.parameters.nb-users}}-{{inputs.parameters.nb-courses}}-1.sql"
          accessKeySecret:
            name: argo-artifacts
            key: accesskey
          secretKeySecret:
            name: argo-artifacts
            key: secretkey
#######################################        
  - name: helm-remove-moodle
    inputs:
      parameters:
      - name: size
      - name: nb-users
      - name: nb-courses    
    script:
      image: alpine/helm
      command: [sh]    
      source: |-
        export XP_NAME={{workflow.parameters.xp-name}}-{{inputs.parameters.size}}-{{inputs.parameters.nb-users}}-{{inputs.parameters.nb-courses}}
        helm delete $XP_NAME
        